/**
 * DataPass V2.2 exchange envelopes (contract version 0.1-draft).
 *
 * Ported 1:1 from handoff/v2.2/contracts/contract_kit.py. tests/contracts.parity.test.ts
 * compares the emitted JSON Schemas with fixtures generated by that Python kit, so any
 * divergence is a deliberate, reviewed change rather than drift.
 */
import { anyOf, arr, BOOL, constOf, DIGEST, enumOf, ID, NULL, obj, TEXT, TIME, type Schema } from "./schemaDsl";

export const CONTRACT_VERSION = "0.1-draft";
export const ENVELOPE_KINDS = ["io-contract", "app-exchange", "authority-snapshot", "architecture-view", "publication-brief"] as const;
export type EnvelopeKind = typeof ENVELOPE_KINDS[number];

const REFS = arr(ID);
export const HASH = obj({ algorithm: constOf("sha256"), value: DIGEST });
export const BASIS_SCHEMA = enumOf("source-reported", "assumption", "model-output", "measured", "target");
const CLASS = enumOf("public", "internal", "confidential");
export const SOURCE_SCHEMA = obj({
  id: ID, authority: TEXT, recordRef: TEXT, revision: TEXT,
  observedAt: TIME, classification: CLASS, snapshotHash: HASH
});
const ARTIFACT = obj({
  id: ID, locatorRef: ID, mediaType: TEXT, schemaRef: TEXT,
  byteHash: HASH, inputRefs: REFS, producerRef: ID
});
const PORT = obj({
  id: ID, direction: enumOf("in", "out"), contractRef: ID,
  dataMode: enumOf("snapshot", "stream", "request", "result"),
  required: BOOL
});
const BASE = obj({
  scopeRevision: TEXT, manifestHash: HASH,
  repositories: arr(obj({ repoRef: ID, revision: TEXT, workingTreeHash: HASH }), 30)
});

function envelope(kind: EnvelopeKind, payload: Schema): Schema {
  const schema = obj({
    format: constOf("datapass." + kind),
    contractVersion: constOf(CONTRACT_VERSION), id: ID, projectRef: ID,
    scopeRef: ID, base: BASE, classification: CLASS,
    createdAt: TIME, sources: arr(SOURCE_SCHEMA), payload
  }) as Extract<Schema, { type: "object" }>;
  return { ...schema, $schema: "https://json-schema.org/draft/2020-12/schema" };
}

export const SCHEMAS: Record<EnvelopeKind, Schema> = {
  "io-contract": envelope("io-contract", obj({
    schemaRef: TEXT, compatibility: enumOf("exact", "backward", "assessment-required"),
    grain: TEXT, keys: arr(TEXT, 20), units: arr(obj({ field: TEXT, unit: TEXT }), 50),
    timeSemantics: TEXT, delivery: enumOf("snapshot", "at-least-once", "request-response"),
    qualityChecks: arr(TEXT, 50), retentionPolicyRef: ID, ports: arr(PORT, 30)
  })),
  "app-exchange": envelope("app-exchange", obj({
    direction: enumOf("request", "result"), correlationId: ID,
    appRef: ID, operation: enumOf("prepare-candidate", "validate", "package", "describe"),
    inputRefs: REFS, outputArtifacts: arr(ARTIFACT, 50),
    requestHash: anyOf(HASH, NULL), resultState: enumOf("not-run", "succeeded", "failed", "partial"),
    executionEvidenceRef: anyOf(ID, NULL)
  })),
  "authority-snapshot": envelope("authority-snapshot", obj({
    querySpecRef: ID, querySpecHash: HASH, asOf: TIME,
    state: enumOf("complete", "partial", "empty", "error", "not-authorized"),
    recordRefs: REFS, omissions: arr(TEXT), nextCursorAvailable: BOOL,
    encoding: enumOf("json", "mongodb-canonical-ejson"), dataArtifactRef: anyOf(ID, NULL)
  })),
  "architecture-view": envelope("architecture-view", obj({
    semanticRevision: TEXT, layoutRevision: TEXT,
    mode: enumOf("active-engineering", "learning", "portfolio-reconstruction", "reference"),
    nodes: arr(obj({
      id: ID, itemRef: ID, label: TEXT,
      evidenceRefs: REFS, state: enumOf("planned", "observed", "unknown")
    }), 200),
    edges: arr(obj({
      id: ID, source: ID, target: ID,
      relation: enumOf("consumes", "produces", "runsOn", "observedBy", "dependsOn")
    }), 500),
    omissions: arr(TEXT), publication: constOf("not-authorized")
  })),
  "publication-brief": envelope("publication-brief", obj({
    audience: enumOf("internal", "named-reviewers", "public"),
    purpose: TEXT, outputFormats: arr(enumOf("pptx", "pdf", "docx", "web"), 4, 1),
    claims: arr(obj({
      id: ID, statement: TEXT, basis: BASIS_SCHEMA, sourceRefs: REFS,
      review: enumOf("draft", "approved", "rejected"),
      limitations: arr(TEXT), allowedAudiences: arr(enumOf("internal", "named-reviewers", "public"), 3)
    })),
    assetRefs: REFS, releaseState: enumOf("draft", "reviewed-for-generation"),
    publication: constOf("not-authorized")
  }))
};

// ---- TypeScript shapes matching the schemas ----

export type Classification = "public" | "internal" | "confidential";
export type Audience = "internal" | "named-reviewers" | "public";
export interface HashRef { algorithm: "sha256"; value: string }
export interface SourceRef {
  id: string; authority: string; recordRef: string; revision: string;
  observedAt: string; classification: Classification; snapshotHash: HashRef;
}
export interface BaseRef {
  scopeRevision: string; manifestHash: HashRef;
  repositories: Array<{ repoRef: string; revision: string; workingTreeHash: HashRef }>;
}
export interface Envelope<K extends EnvelopeKind = EnvelopeKind, P = Record<string, unknown>> {
  format: `datapass.${K}`;
  contractVersion: typeof CONTRACT_VERSION;
  id: string; projectRef: string; scopeRef: string;
  base: BaseRef; classification: Classification; createdAt: string;
  sources: SourceRef[];
  payload: P;
}
export interface ArtifactRef {
  id: string; locatorRef: string; mediaType: string; schemaRef: string;
  byteHash: HashRef; inputRefs: string[]; producerRef: string;
}
export interface AppExchangePayload {
  direction: "request" | "result"; correlationId: string; appRef: string;
  operation: "prepare-candidate" | "validate" | "package" | "describe";
  inputRefs: string[]; outputArtifacts: ArtifactRef[];
  requestHash: HashRef | null; resultState: "not-run" | "succeeded" | "failed" | "partial";
  executionEvidenceRef: string | null;
}
export interface AuthoritySnapshotPayload {
  querySpecRef: string; querySpecHash: HashRef; asOf: string;
  state: "complete" | "partial" | "empty" | "error" | "not-authorized";
  recordRefs: string[]; omissions: string[]; nextCursorAvailable: boolean;
  encoding: "json" | "mongodb-canonical-ejson"; dataArtifactRef: string | null;
}
export interface ArchitectureViewPayload {
  semanticRevision: string; layoutRevision: string;
  mode: "active-engineering" | "learning" | "portfolio-reconstruction" | "reference";
  nodes: Array<{ id: string; itemRef: string; label: string; evidenceRefs: string[]; state: "planned" | "observed" | "unknown" }>;
  edges: Array<{ id: string; source: string; target: string; relation: "consumes" | "produces" | "runsOn" | "observedBy" | "dependsOn" }>;
  omissions: string[]; publication: "not-authorized";
}
export interface BriefClaim {
  id: string; statement: string;
  basis: "source-reported" | "assumption" | "model-output" | "measured" | "target";
  sourceRefs: string[]; review: "draft" | "approved" | "rejected";
  limitations: string[]; allowedAudiences: Audience[];
}
export interface PublicationBriefPayload {
  audience: Audience; purpose: string; outputFormats: Array<"pptx" | "pdf" | "docx" | "web">;
  claims: BriefClaim[]; assetRefs: string[];
  releaseState: "draft" | "reviewed-for-generation"; publication: "not-authorized";
}
export interface IoContractPayload {
  schemaRef: string; compatibility: "exact" | "backward" | "assessment-required";
  grain: string; keys: string[]; units: Array<{ field: string; unit: string }>;
  timeSemantics: string; delivery: "snapshot" | "at-least-once" | "request-response";
  qualityChecks: string[]; retentionPolicyRef: string;
  ports: Array<{ id: string; direction: "in" | "out"; contractRef: string; dataMode: "snapshot" | "stream" | "request" | "result"; required: boolean }>;
}
