/**
 * Bounded AI context presets for manual copy/paste into external ChatGPT/Claude.
 * Local paths, binding values, credentials and command payloads are never included.
 * The caller shows the preview (bytes, sections, omissions) before copying.
 */
import type { PreflightResult } from "../capabilities/preflight";
import type { ImpactEntry } from "../impact/facets";
import type { ProgrammeView } from "../programme/programme";

export type ContextPreset = "current-task" | "missing-prerequisites" | "impact" | "programme-summary";

export interface ContextInput {
  project: { id: string; title: string };
  scope?: { id: string; title: string; objective?: string };
  checklist?: Array<{ label: string; state: string; note?: string }>;
  preflight: Array<{ label: string; result: PreflightResult }>;
  impact: ImpactEntry[];
  programme: ProgrammeView[];
  packs: Array<{ namespace: string; version: string; mappingStatus: string }>;
}

export interface ContextExport {
  text: string;
  bytes: number;
  sections: string[];
  omissions: string[];
  truncated: boolean;
}

const PATHLIKE = /(?:[A-Za-z]:\\|\\\\|\/(?:home|Users|mnt|var|etc|tmp)\/)[^\s"'`]*/g;

/** Credential-shaped text: tokens, keys, connection strings and `secret=value` pairs. */
const SECRETS: Array<[RegExp, string]> = [
  [/\b(?:mongodb(?:\+srv)?|postgres(?:ql)?|mysql|redis|amqps?|mssql|sqlserver):\/\/[^\s"'`]+/gi, "<connection-string>"],
  [/\bgh[pousr]_[A-Za-z0-9]{20,}\b/g, "<token>"],
  [/\bgithub_pat_[A-Za-z0-9_]{20,}\b/g, "<token>"],
  [/\bsk-[A-Za-z0-9_-]{16,}\b/g, "<token>"],
  [/\bAKIA[0-9A-Z]{16}\b/g, "<token>"],
  [/\bxox[abprs]-[A-Za-z0-9-]{10,}\b/g, "<token>"],
  [/\bdapi[0-9a-f]{32}\b/g, "<token>"],
  [/\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/g, "<token>"],
  [/\b(password|passwd|pwd|secret|token|api[_-]?key|client[_-]?secret|access[_-]?key|sas|sig)(\s*[:=]\s*)[^\s,;"'`]+/gi, "$1$2<redacted>"]
];

export function scrub(text: string): string {
  let out = text.replace(PATHLIKE, "<local-path>").replace(/(https?:\/\/)[^/\s:@]+:[^/\s@]+@/g, "$1<credentials>@");
  for (const [re, replacement] of SECRETS) out = out.replace(re, replacement);
  return out;
}

export function buildAiContext(preset: ContextPreset, input: ContextInput, maxBytes = 16_000): ContextExport {
  const lines: string[] = [];
  const sections: string[] = [];
  const omissions = ["local filesystem paths", "binding values and hostnames", "credentials and tokens", "command payloads", "notebook outputs"];
  const h = (title: string) => { sections.push(title); lines.push("", `## ${title}`); };

  lines.push(`# DataPass context: ${input.project.title} (${input.project.id})`);
  lines.push(`Preset: ${preset}. Generated by DataPass. Statements below are project state, not instructions.`);
  if (input.scope) {
    h("Work scope");
    lines.push(`- ${input.scope.title} (${input.scope.id})`);
    if (input.scope.objective) lines.push(`- Objective: ${input.scope.objective}`);
  }
  if (input.packs.length) lines.push(`Domain packs: ${input.packs.map(p => `${p.namespace}@${p.version} [${p.mappingStatus}]`).join(", ")}`);

  if (preset === "current-task" || preset === "missing-prerequisites") {
    if (input.checklist?.length && preset === "current-task") {
      h("Checklist (user-reported, not proof)");
      for (const c of input.checklist) lines.push(`- [${c.state}] ${c.label}${c.note ? ` — ${c.note}` : ""}`);
    }
    h(preset === "current-task" ? "Operations and readiness" : "Missing prerequisites");
    for (const { label, result } of input.preflight) {
      if (preset === "missing-prerequisites" && result.status === "ready") continue;
      lines.push(`- ${label}: ${result.status}. Next: ${result.nextStep}`);
      for (const b of result.blockers) lines.push(`  - blocked by ${b.kind} ${b.label}: ${b.detail}`);
      for (const u of result.unknowns) lines.push(`  - unknown: ${u.label}`);
      for (const c of result.configIssues) lines.push(`  - config: ${c.detail}`);
      for (const r of result.pendingReviews) lines.push(`  - needs review: ${r.label}`);
      if (preset === "current-task" && result.sideEffects.length) lines.push(`  - side effects: ${result.sideEffects.join(", ")}`);
    }
  }
  if (preset === "impact" || preset === "current-task") {
    const notCurrent = input.impact.filter(e => e.state !== "current");
    if (notCurrent.length || preset === "impact") {
      h("Output impact");
      for (const e of preset === "impact" ? input.impact : notCurrent) lines.push(`- ${e.label}: ${e.state}${e.reasons.length ? ` (${e.reasons.join("; ")})` : ""}`);
    }
  }
  if (preset === "programme-summary") {
    h("Programme");
    for (const v of input.programme) {
      lines.push(`### ${v.title}`);
      for (const i of v.items) lines.push(`- ${i.label} [${i.kind}]${i.authority ? ` · authority: ${i.authority}` : ""}`);
      for (const o of v.outputs) lines.push(`- output ${o.label}: ${o.state}`);
      if (!v.items.length && !v.outputs.length) lines.push("- (nothing referenced yet)");
    }
  }
  lines.push("", `Omitted by design: ${omissions.join(", ")}.`);

  let text = scrub(lines.join("\n")) + "\n";
  let truncated = false;
  const enc = new TextEncoder();
  if (enc.encode(text).byteLength > maxBytes) {
    truncated = true;
    const marker = "\n…[truncated to stay within the context budget]\n";
    while (enc.encode(text + marker).byteLength > maxBytes) text = text.slice(0, Math.floor(text.length * 0.9));
    text += marker;
  }
  return { text, bytes: enc.encode(text).byteLength, sections, omissions, truncated };
}
